[package]
name = "snake"
version = "0.1.0"
authors = ["Alexander Milevski <alex@milevski.co>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.71"
wee_alloc = "0.4.5"
